num = int(input('Insira um número: '))

print(f'{num} x  1 = {(num*1):>3}')
print(f'{num} x  2 = {(num*2):>3}')
print(f'{num} x  3 = {(num*3):>3}')
print(f'{num} x  4 = {(num*4):>3}')
print(f'{num} x  5 = {(num*5):>3}')
print(f'{num} x  6 = {(num*6):>3}')
print(f'{num} x  7 = {(num*7):>3}')
print(f'{num} x  8 = {(num*8):>3}')
print(f'{num} x  9 = {(num*9):>3}')
print(f'{num} x 10 = {(num*10):>3}')
